server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/campus?serverTimezone=Asia/Seoul
    username: myuser
    password: mypassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
  data:
    mongodb:
      uri: mongodb://rootuser:1234@localhost:27017/campus?authSource=admin

external-server:
  metadata:
    url: http://localhost:8088
